version: 2
jobs:
  lint:
    docker:
      - image: cljkondo/clj-kondo:latest
    steps:
      - checkout
      - run:
          name: Lint
          command: clj-kondo --lint src --fail-level error
  test:
    docker:
      - image: cimg/clojure:1.11.1-openjdk-11.0

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx500m

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run:
          name: Test
          command: lein test

workflows:
  version: 2
  workflow:
    jobs:
      - lint
      - test
